
quotes = [
    "I took the road less traveled and that has made all the difference.",
    "It's time to plant the seeds of hope and a new, brighter future.",
    "Be bold. Be courageous. Be your best.",
    "I came, I saw, I conquered.",
    "There's no need to try to fit in, when you were born to stand out.",
    "When you lean into your passions, you can't go wrong.",
    "The things we are racing towards are better than what we leave behind.",
    "The future looks bright and I will keep on shining.",
    "This isn't goodbye, but see you later.",
    "The world is your oyster.",
    "May your cap fly as high as your dreams.",
    "Though our branches grow in different directions, our roots remain as one.",
    "And so the adventure begins.",
    "This is the beginning of everything you want.",
    "Once you become fearless, life becomes limitless.",
    "What feels like the end is often the beginning.",
    "If it excites you and scares you at the same time, it probably means you should do it.",
    "The best way to predict the future is to create it.",
    "Not letting anyone or anything stand in my way.",
    "Whatever is good for your soul, that's what you should do.",
    "Every end has a new beginning.",
    "I believed I could, so I did.",
    "If you can dream it, you can make it so.",
    "Can I take a nap now?",
    "I got the skills to pay the bills.",
    "Turns out I wasn't too cool for school.",
    "Let me put that 'hire me' sign on my front lawn now.",
    "Graduate: (N.) A person who now has carpal tunnel from note-taking.",
    "Very proud, very tired.",
    "Cs really do get degrees.",
    "What, like it's hard?",
    "That's all folks.",
    "I already forgot everything.",
    "Beauty and brains.",
    "Cheers to the memories.",
    "Now, who is going to pay off these loans?",
    "Next stop: Adulting",
    "Some graduate with honors, I am just honored to graduate.",
    "I want to thank Google, Wikipedia, and whoever invented copy and paste.",
    "Call me a chemistry cylinder because I am graduated.",
    "Proud of my B.S.",
    "The tassel was worth the hassle.",
    "Now, it's hotter in here by one degree.",
    "Thank you Mom, Dad, and coffee.",
    "I've already forgotten everything.",
    "I owe my degree to coffee.",
    '''I'm 100% certain that I am zero percent sure of what I'm going to do.''',
    "Cap. Gown. It's going down.",
    "I graduated, so now I'm like all smart and stuff.",
    "How lucky I am to have something that makes saying goodbye so hard.",
    "Make today your day.",
    "Now, everything awaits me.",
    "One step closer.",
    "On to my next adventure.",
    "The first step is just showing up.",
    "Enjoy the journey. Success does not rush.",
    "The beauty of the future is found when you believe in yourself.",
    "Take the risk, make the mistake. It'll all be worth it.",
    "I laugh without fear of the future.",
    "All good things must come to an end, but this is just the beginning.",
    "This is what dreams are made of.",
    "Don't cry because it's over. Smile because it happened.",
    "The best feeling in the world is knowing your parents are smiling because of you.",
    "May we continue to do amazing things in life.",
    "Many dream, some try, but I achieved.",
    "Wherever life plants you, bloom with grace.",
    "Dream big, work hard, stay focused, and surround yourself with good people.",
    "Reach for the stars. You might become one.",
    "Never stop dreaming and never lose your spirit.",
    "The best is yet to come.",
    "Thank U, Next.",
    "Watch out for me, I'm bound to glow.",
    "All work and no play never made me lose it. All business all day keeps me up a level.",
    "What didn't break me, made me better.",
    "For every dark night, there's always a brighter day.",
    "What was once in the windshield, is now in my rear view",
    "Always stay gracious, best revenge is your paper.",
    "It was all a dream.",
    "And if at first you don't succeed, dust yourself off and try again.",
    "Before I had it, I closed my eyes and imagined the good life.",
    "Ain't about how fast I get there, ain't about what's waiting on the other side — it's the climb.",
    "And this is the part where you find out who you are.",
    "I don't know where I'm going, but I'm on my way.",
    "There's just no telling how far I'll go.",
    "As we go on, we remember all the times we had together.",
    "Today is where your book begins. The rest is still unwritten.",
    "It's something unpredictable, but in the end it's right, I hope you had the time of your life.",
    "Goodbye to you. Goodbye to everything that I knew.",
    "I wish that I could have this moment for life. The greatest adventure is what lies ahead.",
    "Did everyone see that? Because I will not be doing it again.",
    "Don't tell me the sky's the limit when there are footprints on the moon.",
    "Kid, you'll move mountains.",
    "One isn't necessarily born with courage, but one is born with potential.",
    "Always be a first-rate version of yourself, instead of a second-rate version of somebody else.",
    "If opportunity doesn't knock, build a door.",
    "Education is the key to unlocking the world, a passport to freedom.",
    "It always seems impossible until it's done.",
    "Success is only meaningful and enjoyable if it feels like your own.",
    "Mischief Managed.",
    "She turned her can'ts into cans, and her dreams into plans.",
    "You can never be overdressed or overeducated.",
    "Dream big and dare to fail.",
    "We know what we are but know not what we may be.",
    "If you can imagine it, you can achieve it; if you can dream it, you can become it.",
    "There are far, far better things ahead than any we leave behind.",
    "I took the road less traveled and that has made all the difference.",
    "It's time to plant the seeds of hope and a new, brighter future.",
    "Be bold. Be courageous. Be your best.",
    "I came, I saw, I conquered.",
    "There's no need to try to fit in, when you were born to stand out.",
    "When you lean into your passions, you can't go wrong.",
    "The things we are racing towards are better than what we leave behind.",
    "The future looks bright and I will keep on shining.",
    "This isn't goodbye, but see you later.",
    "The world is your oyster.",
    "May your cap fly as high as your dreams.",
    "Though our branches grow in different directions, our roots remain as one.",
    "And so the adventure begins.",
    "This is the beginning of everything you want.",
    "Once you become fearless, life becomes limitless.",
    "What feels like the end is often the beginning.",
    "If it excites you and scares you at the same time, it probably means you should do it.",
    "The best way to predict the future is to create it.",
    "Not letting anyone or anything stand in my way.",
    "Whatever is good for your soul, that's what you should do.",
    "Every end has a new beginning.",
    "I believed I could, so I did.",
    "If you can dream it, you can make it so.",
    "Finally graduated: My mission for world domination begins now!",
    "Thank you, teachers, for the A's, now off to adulting… Any advice?",
    "Officially graduated from Teacher's Pet Academy with honors!",
    "Four years of relentless studying, but now I'm a professional over-thinker.",
    "I studied for years to learn how to adult. Wish me luck!",
    "They said I wouldn't make it, but here I am… just a bit more refined!",
    "Proof that even rebels can follow a graduation ceremony!",
    "Officially a graduate, and I did it my way - against all odds!",
    "I may have bent a few rules, but I'm standing tall at graduation!",
    "I ran a few laps, tackled some exams, and now I'm crossing the finish line!",
    "From the field to the stage, I made it!",
    "Creativity fueled my studies, and now it's time to color outside the lines of life!",
    "Graduating with a degree in 'Thinking Outside the Box' - Where's my job?",
    "I didn't study much, but I napped like a pro - now graduating with honors!",
    "I might be lazy, but I still managed to graduate. Go figure!",
    "Graduation.exe has successfully executed. Now, where's the WiFi?",
    "I hacked my way through college - now it's time to conquer the real world!",
    "Spent more time making friends than studying, and I have no regrets!",
    "Officially graduated with a degree in 'Socializing and Networking.' Hire me!",
    "I graduated, and now I'm officially too cool for school!",
    "Diploma: Unlocked. Next Level: Adulting!",
    "Goodbye, GPA. Hello, 9-to-5 life!",
    "I used to be the class clown; now I'm just a graduate clown.",
    "Warning: Fully trained to adult, handle with care!",
    "Finally free from textbooks and curfews!",
    "I came, I saw, I graduated. What's next?",
    "Now a certified expert at Googling everything!",
    "I survived college, and all I got was this piece of paper!",
    "Cheers to the end of all-nighters and Ramen noodles!",
    "No more exams, but the test of life begins!",
    "Graduating with a degree in 'Panic Management.'",
    "Four years of Netflix and occasional studying - I made it!",
    "Officially out of student discounts, but I'm still a bargain!",
    "From all-night parties to graduation day - what a journey!",
    "I didn't choose the graduation life; the graduation life chose me!",
    "I'm not a student anymore, but I'll always be a learner.",
    "Turns out, I'm not just a caffeine addict; I'm also a graduate!",
    "I'm not saying I'm the class clown, but I do know how to graduate with a smile!",
    "Life is tough, but so am I - officially graduated!",
    "Bachelor's degree unlocked! Now, who wants to hire a professional student?",
    "Mastered the art of cramming just in time for graduation!",
    "I may have a bachelor's degree, but I'm still a rookie at adulting.",
    "Mastered the syllabus, but still can't figure out taxes!",
    "They say a bachelor's degree opens doors - now, which one leads to the coffee shop?",
    "Just earned my bachelor's degree. Now, where's my cape and superhero name?",
    "Finally, a Bachelor's degree to prove I'm not just good at Netflix.",
    "Mastered the art of student loans. Anyone hiring a debt expert?",
    "Officially a master of procrastination… I mean, education!",
    "From keg parties to cap and gown - quite the transformation!",
    "Bachelor's degree: Because'professional learner isn't a real job.",
    "I may have a bachelor's degree, but I still can't fold a fitted sheet.",
    "Mastered the classroom, now time to master the office coffee machine!",
    "Mastered the books, but still working on mastering adulting.",
    "They say a bachelor's degree is a smart investment. We'll see about that!",
    "Just graduated with a bachelor's degree in 'Avoiding Responsibilities.'",
    "Mastered the fine art of citing sources and making ramen.",
    "Bachelor's degree: A fancy way to say I'm officially unemployed!",
    "I have a bachelor's degree now, but I still can't parallel park.",
    "I survived high school; now I'm ready to conquer the world… or at least college!",
    "Diploma: Unlocked. Next Level: Adulthood!",
    "Goodbye, high school drama. Hello, real-life drama!",
    "From hall passes to graduation, I made it without detention!",
    "Finally free from textbooks and cafeteria food!",
    "College is like a rollercoaster - and I just got off the ride!",
    "I came, I saw, I graduated. What's next?"
]
